### ISSUE TITLE
Issue with Settings structure

### ISSUE THREAD

**Issue by niliopoulos** [BYU-MicrostructureOfMaterials/OpenXY#14]
Matlab complains about not finding Settings.DoParallel in line 134 of MainGUI.m. I think the line needs to read:
if ~any(strcmp({tb.Name},'Parallel Computing Toolbox')) && handles.Settings.DoParallel > 1

Thanks!

**Comment by dtfullwood** [comment]
Thanks - well spotted. This is now fixed.
DTF
