### ISSUE TITLE
Material File not found

### ISSUE THREAD

**Issue by Fred-Ad** [BYU-MicrostructureOfMaterials/OpenXY#20]
Hi, and thanks for sharing this work

When I try to follow the tutorial, I get an error : 'material file not found'
I checked : the file I selected is in the Materials folder. It doesn't work neither with the use scan file (using the .ang provided).
I use R2019a.

Thank you

**Comment by dtfullwood** [comment]
It is looking for the data file that gives material lattice parameters etc. what material is it? Are you telling it to use the material designated by the scan file or selecting from the options in openXY? Selecting an option in openXY might be safer if it’s a single material type and openXY has a relevant material file.
David

David Fullwood
Mechanical Engineering
Brigham Young University
Provo, Utah 84602
801 422 6316
dfullwood@byu.edu

On Feb 10, 2020, at 8:36 AM, Fred-Ad <notifications@github.com> wrote:

﻿

Hi, and thanks for sharing this work

When I try to follow the tutorial, I get an error : 'material file not found'
I checked : the file I selected is in the Materials folder. It doesn't work neither with the use scan file (using the .ang provided).
I use R2019a.

Thank you

**Comment by Fred-Ad** [comment]
Hi,

I use the tutorial . ang file witch material is ferrite. However, it dosesn't work if I choose 'scan file', nor 'iron-alpha' in the openXY option. I have the same warning window : 'material file not found' when I try to make a pattern center calibration, or if I try to run the cross-correlation.
I just don't understand as I checked that the iron-alpha.txt exists in the openXY material folder.

Thanks for answering so quickly !

**Comment by Fred-Ad** [comment]
Solved !!!
I was working in the Matlab folder, not in the OpenXY folder !!
My fault

Thank you for your advices !!
