### ISSUE TITLE
PC callibration problem

### ISSUE THREAD

**Issue by pnowakow2** [BYU-MicrostructureOfMaterials/OpenXY#32]
Hello, 

I have problems with PC calibration. I used it in the past, and that was working very well. but now I'm getting very odd numbers after PC callibration.
I'm working on data collected using Oxford Instruments AZtec system. 
I used the data from the same system before and all was working ok. 
Now I can not calibrate PC.
Have you heard on similar problem, what do you need from me in order to help. 

Thank you, 
Pawel

**Comment by dtfullwood** [comment]
Perhaps your starting PC is too far off? What PC approach are you using (what settings are you using in the GUI)?
How big is your dataset if I wanted to try it out?
You can email me directly on dfullwood@byu.edu if you want faster response.
Thanks
David

**Comment by eretnek** [comment]
For Oxford you currently have to manually tell the system to read the
pattern center from the tiff files, you do this in the PC calibration GUI.
Once you do this, you should be close enough to calibrate.

**Comment by pnowakow2** [comment]
That works!
Thanks for help!
