### ISSUE TITLE
matlabpool() function not working

### ISSUE THREAD

**Issue by GTerHaar** [BYU-MicrostructureOfMaterials/OpenXY#6]
Hi,

I am using Matlab R2014a. It appears that the "matlabpool()" function does not work.

The function seems to have been removed according to the page below:
http://www.mathworks.com/help/mdce/release-notes.html?searchHighlight=matlabpool

The error message that was generated was:

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Undefined function 'matlabpool' for input arguments of type 'char'.
Error in DislocationDensityCalculate (line 147)
        ppool = matlabpool('size');
Error in HREBSDMain (line 411)
    DislocationDensityCalculate(Settings,MaxMisorientation,IQcutoff,VaryStepSizeI)
Error in MainGUI>RunButton_Callback (line 423)
    Settings = HREBSDMain(Settings);
Error in gui_mainfcn (line 95)
        feval(varargin{:});
Error in MainGUI (line 42)
    gui_mainfcn(gui_State, varargin{:});
Error in @(hObject,eventdata)MainGUI('RunButton_Callback',hObject,eventdata,guidata(hObject))

Caused by:
    OpenXY encountered an error. Re-select the scan file to reset. 
Error while evaluating uicontrol Callback

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

The webpage below suggests that I use  parpool instead.
http://www.mathworks.com/help/mdce/release-notes.html?searchHighlight=matlabpool

Any help on this?

**Comment by bjack205** [comment]
As mentioned in the documentation, OpenXY requires the parallel processing toolbox for Matlab. You are seeing this error because it attempts to start a parallel pool with the current 'ppool' command, but fails so then tries the legacy command 'matlabpool'. We may be removing the requirement to have the parallel processing toolbox in the future.

**Comment by eretnek** [comment]
In the mean time, you can make the change yourself just by changing a
single instance of "parfor" in HREBSDmain to "for" and another such
instance in Dislocation density calculate.  All other commands that throw
errors  due to licensing at that point can simply be commented out.
