### ISSUE TITLE
File formats

### ISSUE THREAD

**Issue by GTerHaar** [BYU-MicrostructureOfMaterials/OpenXY#7]
Hi,

At the moment the file formats I have were generated from HKL Channel5 software. The file format is a .crc and .cpr files. 

Does anyone know of a way of converting .crc files to .ang files.

Secondly, is there a way to generate the grain.txt file from software such as MTEX or other?

regards

**Comment by eretnek** [comment]
You need to generate a .ctf file from AZtec, that format can be read by OIM
and turned into an .ang file or read directly into OpenXY.

**Comment by bjack205** [comment]
OpenXY has it's own internal algorithm for identifying grains for HKL scans, similar to the method used by OIM. All you need to run OpenXY is the .ctf file and the .cpr file.

**Comment by GTerHaar** [comment]
Thanks for the help!
